#!/usr/bin/env python3
"""
Sanitize pandoc specific syntax from markdown files before using with mkdocs.
"""

import re
import sys

PATTERNS = dict(
    citation = (re.compile(
r"\[@blundell2014;@kebschull2018\]"),'[@blundell2014]^,^[@kebschull2018]'
) ,
    pagebreak=(re.compile(r"\\pagebreak"), ""),
    unnumbered=(re.compile(r"{.*\.unnumbered}"), ""),
    comments=(re.compile(r"<!--.*-->"), ""),
    headers=(re.compile(r"^#"), "##"),
)


def replace(line):
    for _, (pattern, txt) in PATTERNS.items():
        line = pattern.sub(txt, line)
    return line


def main():
    for line in sys.stdin:
        sys.stdout.write(replace(line))


if __name__ == "__main__":
    main()
