#!/usr/bin/env bash

if ! [ -x "$(command -v rclone)" ]; then
	echo "rclone not found"
fi

current=$(find -maxdepth 1 -type f -name "protocol*.pdf" -printf "%p ")
num_results=$(find -maxdepth 1 -type f -name "protocol*.pdf" | wc -l)

echo "found:"
echo $current
echo

if [[ $num_results -ne 1 ]]; then
	echo "expected only one protocol file"
	if [[ $num_results -eq 0 ]]; then
		echo "found none"
		echo "run 'make pdf'"
	fi
	if [[ $num_results -gt 1 ]]; then
		echo "found multiple"
		echo "run 'make clean pdf'"
	fi
	echo "not transferring"
	exit 1
fi

rclone copyto $current u:Protocols/clonmapper-protocol.pdf --box-root-folder-id 88733442029 -vv "$@"
